### ISSUE TITLE
你好，请问有论文中画TSNE图的代码吗

### ISSUE THREAD

**Issue by acu754** [SakurajimaMaiii/TSD#1]

**Comment by SakurajimaMaiii** [comment]
Hello, thanks for your interest in this work. 
For tsne visualization, we use [TSNE from sklearn](https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html).
[Here](https://danielmuellerkomorowska.com/2021/01/05/introduction-to-t-sne-in-python-with-scikit-learn/) is an example. 
For any algorithm (e.g. TSD), you can use `adapt_model.featurizer(x)` to get the feature of input `x`.

**Comment by acu754** [comment]
> 您好，感谢您对这项工作的关注。对于tsne可视化，我们使用[sklearn的TSNE](https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html)。 [下面是](https://danielmuellerkomorowska.com/2021/01/05/introduction-to-t-sne-in-python-with-scikit-learn/)一个示例。对于任何算法（例如TSD），都可以使用来获取输入的特征。`adapt_model.featurizer(x)``x`

Ok, I see. Thank you very much.
