### ISSUE TITLE
The question about the medical segmentation dataset

### ISSUE THREAD

**Issue by mingsiliu557** [SakurajimaMaiii/TSD#10]
Dear author,
 Could you provide me with the link and file structure for the medical segmentation dataset?

**Comment by SakurajimaMaiii** [comment]
Thanks for your interests.
**(a)** For optic disc and cup segmentation, see https://drive.google.com/file/d/1B7ArHRBjt2Dx29a3A6X_lGhD0vDVr3sy/view. We use domain3 (REFUGE) as the source domain and domain1 (Drishti-GS)/domain2(RIM-ONE_r3) as two target domains. You can download it from google drive.
**(b)** For cardiac structure segmentation, we use ACDC (see https://www.creatis.insa-lyon.fr/Challenge/acdc/databases.html) as the source domain and use LGE images in MSCMR2019 (https://zmiclab.github.io/zxh/0/mscmrseg19/index.html) as the target domain. You can download datasets from corresponding links.
**(c)** For prostate dataset, you could download MSD05 dataset from [Google Drive](https://drive.google.com/drive/folders/1HqEgzS8BV2c7xYNrZdEAnrHk7osJJ--2?usp=sharing), and Promise12 dataset from https://promise12.grand-challenge.org/Download/.

**Comment by mingsiliu557** [comment]
Thanks!

SakurajimaMaiii ***@***.***>于2023年11月3日 周五00:00写道：
