### ISSUE TITLE
请问batch_size会影响精度吗

### ISSUE THREAD

**Issue by acu754** [SakurajimaMaiii/TSD#2]
因为预设的batch_size是32，我的电脑跑不动，只能下调至16，然后模型跑出来的效果只有82的精度，达不到论文的效果
![image](https://github.com/SakurajimaMaiii/TSD/assets/68725193/fc7f58b2-49b4-447b-b383-90d404fa31dd)

然后我的TSNE可视化效果是这样的，不知道正不正常，还请您能够解惑
![image](https://github.com/SakurajimaMaiii/TSD/assets/68725193/f9720bfb-00b1-4c7f-af06-e19f01b4685b)

**Comment by SakurajimaMaiii** [comment]
1. batch size是会影响最后结果的，可以看文中的 Fig.5 
2. 做TTA的时候，默认的batch size是128，显存不够可以降低batch size，但是结果会下降，一般来说batch size越大越好
3. 从TSNE上看，**左边的baseline的模型不太正常，你可以先check一下 baseline的性能**，在source domain上训练完模型后，可以在那个文件夹下 done.txt 看到baseline模型在target domain的性能。正常来说， resnet50在PACS上的性能应该是84.5上下（4个domain平均，在 域 123上训练，0上直接测试的结果大概是82.5），你可以看论文的 Tab.15 。

**Comment by acu754** [comment]
左边那个图其实是单纯用原始数据集画的，这个才是ERM的效果，确实没有TSD好。
![image](https://github.com/SakurajimaMaiii/TSD/assets/68725193/f9eacdf9-7e0e-4582-a803-94dd86d3abd2)

训练的时候我batch size设的是16，然后这是结果，跑了好几次都是78
![image](https://github.com/SakurajimaMaiii/TSD/assets/68725193/d88de759-d872-44e1-8592-2c330a80f024)

**Comment by SakurajimaMaiii** [comment]
感觉你的ERM的模型结果有点低，正常来说，
1）ERM在 PACS 选择art（0）作为target domain的时候，应该结果有82.5上下，用TSD在target domain更新以后能有 87.7左右，**提升幅度大概有5个点左右**
2）你这里ERM的结果是78，用了TSD以后是82左右，**涨了4个点，涨点幅度其实还在合理范围的**。
如果计算资源不够的话，可以用resnet18看看，按照论文中的参数来，应该能获得和论文中差不多的结果。
如果ERM的结果和论文里不太对的上，你看一下用TSD前后的涨点幅度也可以。

**Comment by acu754** [comment]
好的，我还想问一下，不同的adapt_model，`adapt_model.featurizer(x)`的效果是如何不同的，我看TTA的算法里面都是`self.featurizer = model.featurizer`，既然用的model都一样(比如说ERM)，那它们(TTA的算法)的featurizer不都是同一个算法(ERM)的featurizer吗，不明白是怎么产生不同的效果的，感觉挺奇妙的。

**Comment by SakurajimaMaiii** [comment]
不同算法刚开始加载的模型参数都是ERM的参数，但是后面更新用的算法不同，导致 `adapt_model.featurizer`的参数变化了。
