### ISSUE TITLE
关于offfice home数据集上的结果

### ISSUE THREAD

**Issue by yoona-unicorn** [SakurajimaMaiii/TSD#7]
我想问下在office-home上 resnet18和resnet50的source model在target数据集上的准确率大概是多少？我在office-home上最后的结果差了四五个点，只跑到了64。我在考虑是不是source model的问题，因为我在PACS上可以得到和论文相同的结果。

**Comment by SakurajimaMaiii** [comment]
你可以看论文里表1和2的结果， officehome上 source model 在target上，resnet18是63.12  renet50是 67.37 (三个随机种子平均)，加上我们的方法分别是 64.83 和 68.67。 你可以先check一下source model的性能。
